### ISSUE TITLE
Type annotations

### ISSUE THREAD

**Issue by layday** [pfmoore/editables#10]
Would annotating the public API be a welcome addition?  I would only be adding type annotations in a PR - I won't be touching any of this project's infrastructure, e.g. to get mypy running in CI.

**Comment by pfmoore** [comment]
Yes, it would. I've not done much with type annotations, but I'd be happy to get them added. I'll happily handle adding the infrastructure side of things.

**Comment by pfmoore** [comment]
Added in #14
