### ISSUE TITLE
Can I use editables in setup.py?

### ISSUE THREAD

**Issue by cafhach** [pfmoore/editables#12]
I would like to create an editable version of my package for local development. I cannot figure out how to combine the editable API with my `setup.py` though. The wheel-API you use in your README appears to be pseudocode?

**Comment by pfmoore** [comment]
The editable library is for build *backends* (like setuptools, flit, etc) to implement editable support (typically for PEP 660, which provides standard functionality for backends to support editable installs). It's not intended for individual projects to implement "editable versions".

But I'm confused, becaus if you're using `setup.py` you are using setuptools which already supports editable installs (via the legacy `setup.py develop` approach supported by pip) so why do you need *anything* special?

**Comment by cafhach** [comment]
I haven't managed to use `setup.py develop` for my package since it has a lot of binary dependencies which are only put into the correct spot by an actual installation of the wheel.

**Comment by pfmoore** [comment]
That's something you need to raise as an issue with setuptools. This library won't help you, I'm afraid.
