### ISSUE TITLE
Merging two trees with files (meson)

### ISSUE THREAD

**Issue by FRidh** [pfmoore/editables#13]
I'm looking into adding support for editable installs to `mesonpep517`. With meson builds are done out of tree. For an editable installation, we have the original source tree, and the `builddir` containing the binary modules. By default the meson build directory mimics the layout of the source tree. Therefore, "simply" merging the two layouts should result in a layout of a working package. This will require a custom loader, and I was wondering whether `editables` covers this case. 

Let's consider the source tree `scipy`, with in it the build tree `builddir`. Say I have the binary
```sh
scipy/builddir/scipy/io/matlab/mio_utils.cpython-38-x86_64-linux-gnu.so
```
Am I correct one would have to pass
```py
my_project.map("scipy.io.matlab.mio_utils", "scipy/builddir/scipy/io/matlab/mio_utils.cpython-38-x86_64-linux-gnu.so")
```

**Comment by pfmoore** [comment]
Yes, that looks right.

**Comment by FRidh** [comment]
Thank you! It's difficult to test parts now when various parts (e.g. pip) are not yet in place.

Relevant mesonpep517 issue https://gitlab.com/thiblahute/mesonpep517/-/issues/10.
