### ISSUE TITLE
Missing version tags

### ISSUE THREAD

**Issue by kloczek** [pfmoore/editables#16]
According to https://pypi.org/project/editables/ latest vesrion is 0.2 however here there is no any version git tags whicg would allow download 0.2 source tree.
Issue is that pypi sdist tar ball is not included test suite.

**Comment by mgorny** [comment]
Please push the tags. It literally takes a few seconds, and it is crucial to distribution packaging. Distributions need a stable archive of sources, and the only stable archives GitHub provides are archives for tags.

**Comment by mgorny** [comment]
@kloczek, if that's any help to you, I've forked the project and pushed a tag. I'm not 100% whether it's commit-exact with the release since the most recent changes are in files not in sdist but it should help you package the thing.

**Comment by pfmoore** [comment]
I don't have tags for the existing versions - I simply didn't tag the versions I released from, so I can't "just push" the tags as they don't exist, even in my local repo.

You should be able to package using the sdist, and I will update the processes to tag when I release. So there should be tags for *future* releases, at least. Although I don't currently have plans for a release.

**Comment by mgorny** [comment]
sdist doesn't include tests.

**Comment by pfmoore** [comment]
Correct. Tests should be run from a git checkout. See [this comment](https://discuss.python.org/t/should-sdists-include-docs-and-tests/14578/4) for my view on including tests in sdists.

**Comment by mgorny** [comment]
I've never requested tests to be included in sdist or even suggested using sdist.

**Comment by pfmoore** [comment]
Sorry - I misunderstood your comment "sdist doesn't include tests".

**Comment by pfmoore** [comment]
Version 0.3 has just been released and there's a git tag here for it. I've added a script to bump the version and make the tag, so hopefully I won't forget tags in the future 😉

**Comment by kloczek** [comment]
Thank you 😃
