### ISSUE TITLE
Version on PyPI greater than repo

### ISSUE THREAD

**Issue by ofek** [pfmoore/editables#19]
Just FYI that they're out of sync, noticed when reviewing https://github.com/conda-forge/editables-feedstock/pull/1

**Comment by pfmoore** [comment]
Thanks. Fixed. Apparently if I `git push --tags` it pushes the tag, but *not* the commit the tag points to. I've no idea what you would have got if you'd tried to pull the 0.3 tag from github before I pushed the commit.

How to design a UI - the git approach 🙁
