### ISSUE TITLE
does not detect Python 3 "no __init__.py" modules, or top-level *.py

### ISSUE THREAD

**Issue by dholth** [pfmoore/editables#3]
Should probably pass explicit `includes` for the no-`__init__.py` case. Haven't tested explicit includes for the top-level `*.py` case.

**Comment by pfmoore** [comment]
Can you clarify? I've no idea what you mean here.

**Comment by dholth** [comment]
suppose you have a layout `src/spammodule/spam.py` without a `src/spammodule/__init__.py`. Then you would need to pass `spammodule` to `editables` as an `includes`.

**Comment by pfmoore** [comment]
Ah, OK. This is being discussed in #4

**Comment by ofek** [comment]
That case can/should be covered by backends themselves, but this library does indeed not yet support top-level/single-file packages. After that, I'd consider this feature-complete.

**Comment by pfmoore** [comment]
Hmm, looking at it, it seems to put the whole source directory on `sys.path`, so it doesn't respect `py_modules` as such, instead it just exposes everything (for fun, try `import setup` after you installed such a directory in editable mode...)

Personally, I'd suggest that PEP 517 editable mode support simply declares this case as invalid. Or more precisely, it states that backends do not have to support exposing top-level files in editable mode - if people want to do that, they can create a package with just an `__init__.py` file.

But I don't actually think this is something that should be decided here - it should be taken back to the Discourse for inclusion in the PEP.

**Comment by ofek** [comment]
> I'd suggest that PEP 517 editable mode support simply declares this case as invalid. Or more precisely, it states that backends do not have to support exposing top-level files in editable mode - if people want to do that, they can create a package with just an __init__.py file.

Sounds good to me 👍 I personally have never understood the purpose of such packages

**Comment by gaborbernat** [comment]
Couldn't the editable module work around this by translating a single module to a package with a single ``__init__.py`` in it (during the build, that is).

**Comment by pfmoore** [comment]
That's a good idea. It should be possible to detect single modules in the `expose` argument to `build_editable` and generate a filename of `{pkg}/__init__.py` with suitable redirector code, so it wouldn't even need an API change.

I'll work on that.

**Comment by gaborbernat** [comment]
This would be another carrot why people should use the new editable mode standard 😉

**Comment by ofek** [comment]
I'm not sure what the scope of this library is actually. Do we expect backends to forego their extant inclusion/exclusion mechanisms or a hybrid approach where this library is passed results of those mechanisms? If the latter, then I think of the proposed features (no `__init__.py` modules, top-level/single-file packages, namespaced packages from #4), the implementation should support exactly all or none.

**Comment by pfmoore** [comment]
In my view, the scope of this library is *currently* just to capture the mechanism of "use an import hook to have an importable module that references code in a different location". So basically, the content of the file that gets installed.

The `build_editable` function is, in that context, simply a convenience wrapper to deliver that standard chunk of code.

I'd be happy to have this library extend its scope somewhat (at the moment there's a trivial amount of "discover what to expose" logic in `build_editable` which could be extended) but I don't want to get into the business of actually building a wheel, as the backend is already handling that side of things.

If you want to discuss the scope further, I'd suggest opening a new issue, with any particular ideas you have.

**Comment by pfmoore** [comment]
Update: To be clear on the status, the current code does not handle "single file" modules, nor does it handle namespace packages.

The problem with single file modules is probably relatively shallow - the machinery should handle it¹ but the implementation of the API doesn't. The problem with namespace packages is more fundamental. If `foo` is a namespace package, there's nothing we can replace with a "self-replacing" module. Possibly the bootstrapper could be modified to handle being installed as `foo.py` in that case, but I'm not sure.

I'm happy to take PRs that address these issues, but I'm currently working on a replacement mechanism based on using a metapath hook. If that works out, the API will change significantly, and the library will get split into two parts - a generic "import redirection" component that can be used independently of editable installs (but which will still have editable installs as its primary use case) and a helper library that build backends can use to handle the admin around creating a set of installable files to drive that library.

¹ For `.py` files at least, C extensions might work but I'm less sure about them...

**Comment by pfmoore** [comment]
See [this post on Discourse](https://discuss.python.org/t/standardising-editable-mode-installs-runtime-layout-not-hooks/4098/99) for details, but this library will, for the foreseeable future, not support exposing namespace packages in editable mode.

Single-file modules will be handled by the current rewrite, once that's complete.

**Comment by pfmoore** [comment]
See #7. The new API covers single-file modules, and setuptools-style `.pth` based addition of a directory is included as an option for namespace packages.

**Comment by pfmoore** [comment]
I'm going to close this, as I believe everything that can be provided here is now covered.
