### ISSUE TITLE
Support namespaced packages

### ISSUE THREAD

**Issue by ofek** [pfmoore/editables#4]
Would that be possible with the current approach?

**Comment by pfmoore** [comment]
I don't know, to be honest. Can you give an example of the precise usage you'd want to support?

For comparison, does setuptools currently support namespaced packages in `setup.py develop`?

**Comment by ofek** [comment]
For example https://github.com/DataDog/integrations-core where the namespace is `datadog_checks`

```
apache
├── datadog_checks
│   └── apache
│       └── __init__.py
├── setup.py
...
postgres
├── datadog_checks
│   └── postgres
│       └── __init__.py
├── setup.py
```

Yes, `pip install --editable ./path` supports namespaced packages as long as all are installed with `--editable`

**Comment by pfmoore** [comment]
OK. I can look into this.

It would be a lot easier if you could provide a reproducible example showing what happens now and based on that describe what you'd want to happen.

Also, have you tried using the `expose` argument to `build_editable`? Is the problem simply that the *default* is only to expose directories containing an `__init__.py`?

**Comment by ofek** [comment]
The issue is that for each install the file name is the namespace e.g. `datadog_checks.py`, thus overwriting the previous with a different `location` rather than a cumulation of locations

**Comment by pfmoore** [comment]
OK. What I'm not clear about, I think, is whether you're reporting a bug or exploring design options here. I've not used namespace packages myself, so I don't have any great insights into how they should be handled (either as editable installs, or as normal ones).

It seems to me that if you have wheels containing the directory `datadog_checks` with an `apache.py` (or `postgres.py`, depending on the wheel) redirector underneath that, then installing these would work as I think you want. Is that correct? If not, can you tell me what fails?

**Comment by ofek** [comment]
A bug.

So using the example:

```
apache
├── datadog_checks
│   └── apache
│       └── __init__.py
├── setup.py
...
postgres
├── datadog_checks
│   └── postgres
│       └── __init__.py
├── setup.py
```

installing both namespaced packages normally you'd get the following:

```
site-packages
├── datadog_checks
│   └── apache
│       └── __init__.py
│   └── postgres
│       └── __init__.py
```

Now using this library, installing the `apache` namespaced package you'd get the following:

```
site-packages
├── datadog_checks.py
```

The `location` variable in `datadog_checks.py` will point to the `apache` directory containing `setup.py`. This works to expose the  `apache` namespaced package e.g. `from datadog_checks.apache import ...`.

Then if you install the  `postgres` namespaced package, `datadog_checks.py` will be overwritten and the `location` variable will now point to the `postgres` directory containing `setup.py`, thus no longer exposing `datadog_checks.apache`.

**Comment by pfmoore** [comment]
As I described above, I think you shouldn't be installing a `datadogs_checks.py`, but rather `datadogs_checks/apache.py` and `datadogs_checks/postgres.py`.

So what you'd end up with is:

```
site-packages
└── datadog_checks
    └── apache.py
    └── postgres.py

```

It would definitely be useful to have better documentation on how to use this library to implement namespace packages, but at this point, my feeling is that the bug is in the backend, not in this library.

**Comment by ofek** [comment]
Ah, I see. I'll try tonight.

**Comment by pfmoore** [comment]
Cool. If it does work, I'll add a worked example to the README. Although at some point we probably need some real documentation...

**Comment by ofek** [comment]
That was a bit rough but now it works: https://pypi.org/project/hatchling/0.0.11/

If it detects a namespaced package, it puts that subpackage under the namespace in the wheel, otherwise it makes a simple top-level `site-packages/package.py`

```python
exposed_packages = {}
for included_file in self.recurse_project_files():
    # Simplify and only look for top-level subpackages e.g. a/b/*.py
    parts = included_file.relative_path.split(os.sep)[:3]

    packages = exposed_packages
    for part in parts:
        packages = packages.setdefault(part, {})

for root_package, possible_packages in exposed_packages.items():
    # Single-file packages are not yet supported: https://github.com/pfmoore/editables/issues/3
    if not possible_packages:
        continue

    subpackages = []
    submodules = []

    for possible_package, possible_subpackages in possible_packages.items():
        if possible_subpackages:
            subpackages.append(possible_package)
        else:
            submodules.append(possible_package)

    # Assume namespaced package
    if subpackages and (not submodules or submodules == ['__init__.py']):
        location = os.path.join(self.root, root_package)
        for filename, content in build_editable_wheel(location, expose=subpackages):
            archive.write_file('{}/{}'.format(root_package, filename), content)
    else:
        for filename, content in build_editable_wheel(self.root, expose=[root_package]):
            archive.write_file(filename, content)
```

**Comment by pfmoore** [comment]
> That was a bit rough but now it works

Excellent. I assume by that you mean that working out precisely what to put in your wheel is complicated, but the machinery this library provides works. That's good, because it means that the mechanism handles the namespace package case.

Is there anything in the API here that would have made this easier for you?

**Comment by ofek** [comment]
> Is there anything in the API here that would have made this easier for you?

Nope, just more docs or examples! Thank you 🙂
